import { Flex, Box, Heading, PseudoBox, Text } from '@chakra-ui/core'
import React, { useState } from 'react'
import { Link } from 'gatsby'
import Hero from '../../Molecule/Hero/Hero'
import CustomQuote from '../../Molecule/CustomQuote/CustomQuote'
import TextList from '../../Atom/TextList/TextList'
import SectionWithImages from '../../Molecule/SectionWithImages/SectionWithImages'
import BlogPreview from '../../Molecule/BlogPreview/BlogPreview'
import './MultiFamilyPage.css'

function MultiFamilyPage () {
  return (
    <Box className="multifamily-page">
      <Flex
        className="hero-wrapper"
        flexDirection="row"
        flexWrap="wrap"
        position="relative"
        justifyContent="center"
        w="100%"
        pt={{ sm: '0', md: '6' }}
        pb={{ sm: '4', md: '6' }}
        px={{ sm: '1rem', md: '9rem' }}
        color="white.500"
      >
        <Hero
          isAlternate
          image="team-page"
          imageAlt="team-page"
          title="Multifamily"
        >
          <p>
            Ask any seasoned real estate investor about how to diversify a real estate portfolio and most willtell you the same thing: multi-family real estate.
          </p>
          <br />
          <p>
            From rural duplexes to full apartment buildings in bustling cities, multi-family real estate has consistently proven to be a profitable investment strategy. We’ve put together this comprehensive guide so you can develop a basic understanding about multifamily real estate and how to add it to your growing portfolio.
          </p>
        </Hero>
        <CustomQuote
          title="MultiFamily"
          subtitle="Need To Know"
          subText={<h3>What You Need To Know About Multi-Family Real Estate</h3>}
          description={(
            <div>
              <p>
                There are many reasons why investors are so interested in multi-family real estate. It has long been considered the “next right step” for investors looking to increase cash flow and diversify their portfolios. Some of the main reasons why investors are drawn to multi-family real estate include:
              </p>
              <br />
              <p>
                <strong>Increased Cash Flow Potential</strong>
                <br />
                Single-family properties are meant for, well, single families. This means the revenue generated by the property comes from a single source. Multifamily properties are designed to accommodate multiple tenants, which means multiple streams of income. These kinds of properties are in high demand, and competition for multi-family real estate can be a lot lower than single-family residential property.
              </p>
              <br />
              <p>
                <strong>Less To Manage</strong>
                <br />
                While it may seem like jumping into multi-family real estate will mean a lot more work, it could actually mean the opposite. Having multiple properties in one location could make it much easier to manage than having multiple properties spread out across the city. It is common for investors to hire property management companies to take care of their investments, which means even less day-to-day work for you.
              </p>
              <br />
              <p>
                <strong>Tax Breaks</strong>
                <br />
                Smart investors are always looking for ways to increase income and reduce expenses, and tax breaks are one way to do this. Multi-family investors are entitled to more and larger tax breaks that may not be available to single-family residential investments.
                <br />
                These are just a few reasons why it makes sense to invest in the multi-family property. But knowing why is just the first step. Next, you have to decide what kind of multi-family real estate investment makes the most sense for your lifestyle, resources, experiences, and financial goals.
              </p>
            </div>
          )}
        />
        <SectionWithImages
          my="12rem"
          title="Types of "
          hasSubtitle="Multi-Family Real Estate"
        >
          <TextList hasStar title="Duplex">
            A duplex is a multi-family property that houses two tenants in two different areas. A duplex often looks like a single-family home on the outside but is split down the middle to create two smaller homes. These properties typically have a shared wall (or floor) and sit in the same property and share certain features like the yard and driveway.
          </TextList>
          <TextList hasStar title="Triplex and Quadaplex">
            A triplex is similar to a duplex in that it is one building separated into multiple residential units. A triplex comes in a variety of configurations, but always includes three individual units in a single building. A quadplex is the same idea except it provides four individual units.
          </TextList>
          <TextList hasStar title="Townhouse">
            A townhome community consists of multiple units, often in a row of similar connected homes, that share a roof and foundation, with walls separating the individual units. Townhome residents share a parking lot and community amenities but have their own private entrances.
          </TextList>
          <TextList hasStar title="Apartment/Condos">
            The main difference between apartments and condos comes down to ownership. Apartments are rented out by individual tenants, and condos are units owned by individual owners.
          </TextList>
        </SectionWithImages>
        <SectionWithImages
          my="12rem"
          title="Things To Consider "
          hasSubtitle="When Investing In Multi-Family Real Estate"
        >
          <Text fontSize="xl">There are many similarities between multi-family investment properties and single-family investment properties. But there are a lot of differences too. Before you jump in and take the first step towards investing in an apartment, duplex, or another multi-family unit, consider some of these factors:</Text>
          <TextList hasStar title="Property Management">
            Hiring a property management company can be a great decision for investors. This allows you to invest in multiple properties and not have to be responsible for the day-to-day running and managing of them. Property management companies can help screen tenants, collect rent, perform maintenance, and do all the behind-the-scenes work so you don't have to.
            <br />
            <br />
            Property managers might not be worth the cost if you only have a property or two, but are a critical component if you plan to scale and manage multiple properties.
          </TextList>
          <TextList hasStar title="Financing">
            Financing options are different for multifamily properties than for single-family properties (including multi-unit properties with less than five units). There are certain tax breaks you can take advantage of, and different requirements you have to meet to qualify for these types of loans.
          </TextList>
          <TextList hasStar title="Location">
            Just like with single-family properties, location is vitally important to establishing and maintainingthe value of the investment. Multifamily properties are always in high demand, especially those in desirable areas. One of the most important things to consider when investing in this type of property is proximity to where people want or need to be.
          </TextList>
          <TextList hasStar title="Number Of Units">
            As you get started, you may want to start with a multi-family property that only has two or three units so that you can get a feel for how this particular investment strategy works with your lifestyle. Then, you can gradually move up to larger properties with more units and increase your cash flow significantly.
          </TextList>
        </SectionWithImages>
        <BlogPreview title="Multifamily News" />
        <Box
          width={{ sm: '100%', md: 3 / 4 }}
          className="leading-text"
          mb={{ sm: '5rem', md: '10rem' }}
          mt={{ sm: '5rem', md: '10rem' }}
          position="relative"
        >
          <Heading
            className="leading-text__heading"
            as="h2"
            fontSize={{ sm: '4xl', md: '4xl' }}
            fontWeight="normal"
          >
            There’s a lot to learn when it comes to successfully investing in multi-family real estate, but you don’t have to figure it out all on your own. When you join our mailing list, you are instantly connected with tools and resources you need to diversify your portfolio. Stay up to date with current market analyses, information on recent sales and current listings, and advice about how to dive into multifamily real estate investing with confidence.
          </Heading>
          <PseudoBox
            as="button"
            display="block"
            my={16}
            mx="auto"
            transition=".3s ease-in"
            border="1px"
            px={8}
            py={4}
            width={{ sm: 'auto', md: '50%' }}
            rounded="2px"
            fontSize="lg"
            fontWeight="semibold"
            bg="primary.500"
            borderColor="#ccd0d5"
            color="white"
            _hover={{ bg: 'accent.500' }}
            _active={{
              bg: '#dddfe2',
              transform: 'scale(0.98)',
              borderColor: '#bec3c9',
            }}
            _focus={{
              boxShadow:
                '0 0 1px 2px rgba(88, 144, 255, .75), 0 1px 1px rgba(0, 0, 0, .15)',
            }}
          >
            <Link className="composition__link" fontSize="lg" to="/team">
              Multi-Family Real Estate : Your Next Steps
            </Link>
          </PseudoBox>
        </Box>
      </Flex>
    </Box>
  )
}

export default MultiFamilyPage
